# Rails.application.config_for(:settings).dig(:site, :name)
# Rails.application.config_for(:settings).dig(:site, :only_personal_accounts)
shared:
  only_personal_accounts: true
  site:
    name: AudioRezka
    email: hello@audiorezka.com
    address: Warszawa, Polska
  pro_features:
    - ✅ Топ 100 аудіокниг українською — з приємною озвучкою + pdf
    - 🎧 Ексклюзивні аудіокниги тільки для преміум користувачів
    - 📚 Щотижневі новинки - нові книги кожного тижня
    - 🚀 Завантаження без обмежень - скачуйте будь-які книги офлайн
  plans:
    - id: price_1RVpRpLRcgxgTmfQZANjO18k
      unit_amount: 2900
      currency: PLN
      interval: місяць
    - id: price_1RVpSELRcgxgTmfQSSCA9v4X
      unit_amount: 9900
      currency: PLN
      interval: рік
production:
  plans:
    - id: price_1RVrKrLRcgxgTmfQCguQqoIX
      unit_amount: 2900
      currency: PLN
      interval: місяць
    - id: price_1RVrL9LRcgxgTmfQlbYLNxKU
      unit_amount: 9900
      currency: PLN
      interval: рік
