# Rails.application.config_for(:settings).dig(:site, :name)
# Rails.application.config_for(:settings).dig(:site, :only_personal_accounts)
shared:
  only_personal_accounts: true
  site:
    name: AudioRezka
    email: hello@audiorezka.com
    address: Warszawa, Polska
  pro_features:
    - ✅ Топ 100 аудіокниг українською — з приємною озвучкою + pdf
  plans:
    - id: price_1RVpRpLRcgxgTmfQZANjO18k
      unit_amount: 2900
      currency: PLN
      interval: month
    - id: price_1RVpSELRcgxgTmfQSSCA9v4X
      unit_amount: 9900
      currency: PLN
      interval: рік
production:
  plans:
    - id: price_1RDRzvLRcgxgTmfQZVdAF93B
      unit_amount: 9900
      currency: USD
      interval: month
    - id: price_1RDRzwLRcgxgTmfQZigxB6ZM
      unit_amount: 99900
      currency: USD
      interval: year
